/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.proyectodever;

import java.util.Scanner;

public class App {
    //parte de michael
     // Metodo para convertir de Celsius a Fahrenheit
    public static double celsiusAFahrenheit(double celsius) {
        return (celsius * 9.0 / 5.0) + 32;
    }

    // Metodo para convertir de Fahrenheit a Celsius
    public static double fahrenheitACelsius(double fahrenheit) {
        return (fahrenheit - 32) * 5.0 / 9.0;
    }
  
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int opcion;
// menu principal 
        do {
            System.out.println("\n=== MENU PRINCIPAL ===");
            System.out.println("1. Calcular promedio de 3 notas");
            System.out.println("2. Convertir grados (Celsius <-> Fahrenheit)");
            System.out.println("3. Calcular area de un triangulo");
            System.out.println("4. Salir");
            System.out.print("Elige una opcion (1-4): ");
            opcion = scanner.nextInt();

            switch (opcion) {
                case 1:
                 // proseso para calcular el promedio de 3 notas 
                 // parte de michael 
                case 2:
                 // proseso para convertir de grados a sentigrados o al contrario  
                    System.out.println("\n--- Conversion de Temperatura ---");
                    System.out.println("a) Convertir de Celsius a Fahrenheit");
                    System.out.println("b) Convertir de Fahrenheit a Celsius");
                    System.out.print("Elige una opcion (a/b): ");
                    char subOpcion = scanner.next().charAt(0);
                    if (subOpcion == 'a' || subOpcion == 'A') {
                        System.out.print("Ingresa los grados Celsius: ");
                        double celsius = scanner.nextDouble();
                        double fahr = celsiusAFahrenheit(celsius);
                        System.out.printf("%.2f C equivale a %.2f F\n", celsius, fahr);
                    } else if (subOpcion == 'b' || subOpcion == 'B') {
                        System.out.print("Ingresa los grados Fahrenheit: ");
                        double fahrenheit = scanner.nextDouble();
                        double celsiusResult = fahrenheitACelsius(fahrenheit);
                        System.out.printf("%.2f F equivale a %.2f C\n", fahrenheit, celsiusResult);
                    } else {
                        System.out.println("Opcion no valida.");
                    }
                    break;


                case 3:
                  // proseso para calcular el area de un triangulo

                case 4:
                    System.out.println("Saliendo del programa...");
                    break;

                default:
                 System.out.println("Opcion invalida. Intenta de nuevo.");
            }
        } while (opcion != 4);

        scanner.close();
    }
}