/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.proyectodever;

import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int opcion;
        //menu principal 
        do {
            System.out.println("\n=== MENU PRINCIPAL ===");
            System.out.println("1. Calcular promedio de 3 notas");
            System.out.println("2. Convertir grados (Celsius <-> Fahrenheit)");
            System.out.println("3. Calcular area de un triangulo");
            System.out.println("4. Salir");
            System.out.print("Elige una opcion (1-4): ");
            opcion = scanner.nextInt();

            switch (opcion) {
                case 1:
                 // proseso para calcular el promedio de 3 notas 
                  
                case 2:
                 // proseso para convertir de grados a sentigrados o al contrario  

                case 3:
                  // proseso para calcular el area de un triangulo

                case 4:
                    System.out.println("Saliendo del programa...");
                    break;

                default:
                 System.out.println("Opcion invalida. Intenta de nuevo.");
            }
        } while (opcion != 4);

        scanner.close();
    }
}